name: Build
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.6.0
    - name: Install Go
      uses: actions/setup-go@v3
    - name: ARM runner
      uses: pguyot/arm-runner-action@v2.5.2
      with:
        base_image: raspios_lite_arm64:latest
        cpu: cortex-a7
        copy_artifact_path: dist/ # Copies dist/ to outside of the image
        commands: |
            set -x
            # Build binary
            go build -o server main.go

            # Place binary in dist/ folder
            mkdir dist
            mv server dist/
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: dist/
        retention-days: 7
            
